name: first workflow
on:
    push:
        branches:
            - main
jobs:
    first_job:
        runs-on: ibuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: run a one-line script
              run: echo "hello world"